FROM node:22-alpine

WORKDIR /app

# Kopírování definic závislostí
COPY package*.json ./

# Instalace závislostí
RUN npm install

# Kopírování zbytku zdrojového kódu
COPY . .

# Aplikace běží na portu 3000
EXPOSE 3000

# Spouštěcí příkaz
CMD ["npm", "run", "dev"]
